export const navList = [
    { id: 1, title: 'Home', link: '#Home' },
    { id: 2, title: 'Peoject', link: '#Projects' },
    { id: 3, title: 'About', link: '#About' },
]

export const projectList = [
    {
        id: 1,
        title: 'Expanding Cards',
        image: 'https://50projects50days.com/img/projects-img/1-expanding-cards.png',
        link: 'ExpandingCards',
    },
    {
        id: 2,
        title: 'Progress Steps',
        image: 'https://50projects50days.com/img/projects-img/2-progress-steps.png',
        link: 'ProgressSteps',
    },
    {
        id: 3,
        title: 'Rotating Navigation Animation',
        image: 'https://50projects50days.com/img/projects-img/3-rotating-navigation-animation.png',
        link: 'RotatingNavigationAnimation',
    },
    {
        id: 4,
        title: 'Hidden Search Widget',
        image: 'https://50projects50days.com/img/projects-img/4-hidden-search-widget.png',
        link: 'HiddenSearchWidget',
    },
    {
        id: 5,
        title: 'Blurry Loading',
        image: 'https://50projects50days.com/img/projects-img/5-blurry-loading.png',
        link: 'BlurryLoading',
    },
    {
        id: 6,
        title: 'Scroll Animation',
        image: 'https://50projects50days.com/img/projects-img/6-scroll-animation.png',
        link: 'ScrollAnimation',
    },
    {
        id: 7,
        title: 'Split Landing Page',
        image: 'https://50projects50days.com/img/projects-img/7-split-landing-page.png',
        link: 'SplitLandingPage',
    },
    {
        id: 8,
        title: 'Form Wave',
        image: 'https://50projects50days.com/img/projects-img/8-form-wave.png',
        link: 'FormWave',
    },
    {
        id: 9,
        title: 'Sound Board',
        image: 'https://50projects50days.com/img/projects-img/9-sound-board.png',
        link: 'SoundBoard',
    },
    {
        id: 10,
        title: 'Dad Jokes',
        image: 'https://50projects50days.com/img/projects-img/10-dad-jokes.png',
        link: 'DadJokes',
    },
    {
        id: 11,
        title: 'Event KeyCodes',
        image: 'https://50projects50days.com/img/projects-img/11-event-keycodes.png',
        link: 'EventKeyCodes',
    },
    {
        id: 12,
        title: 'FAQ Collapse',
        image: 'https://50projects50days.com/img/projects-img/12-faq-collapse.png',
        link: 'FAQCollapse',
    },
    {
        id: 13,
        title: 'Random Choice Picker',
        image: 'https://50projects50days.com/img/projects-img/13-random-choice-picker.png',
        link: 'RandomChoicePicker',
    },
    {
        id: 14,
        title: 'Animated Navigation',
        image: 'https://50projects50days.com/img/projects-img/14-animated-navigation.png',
        link: 'AnimatedNavigation',
    },
    {
        id: 15,
        title: 'Incrementing Counter',
        image: 'https://50projects50days.com/img/projects-img/15-incrementing-counter.png',
        link: 'IncrementingCounter',
    },
    {
        id: 16,
        title: 'Drink Water',
        image: 'https://50projects50days.com/img/projects-img/16-drink-water.png',
        link: 'DrinkWater',
    },
    {
        id: 17,
        title: 'Movie App',
        image: 'https://50projects50days.com/img/projects-img/17-movie-app.png',
        link: 'MovieApp',
    },
    {
        id: 18,
        title: 'Background Slider',
        image: 'https://50projects50days.com/img/projects-img/18-background-slider.png',
        link: 'BackgroundSlider',
    },
    {
        id: 19,
        title: 'Theme Clock',
        image: 'https://50projects50days.com/img/projects-img/19-theme-clock.png',
        link: 'ThemeClock',
    },
    {
        id: 20,
        title: 'Button Ripple Effect',
        image: 'https://50projects50days.com/img/projects-img/20-button-ripple-effect.png',
        link: 'ButtonRippleEffect',
    },
    {
        id: 21,
        title: 'Drag N Drop',
        image: 'https://50projects50days.com/img/projects-img/21-drag-n-drop.png',
        link: 'DragNDrop',
    },
    {
        id: 22,
        title: 'Drawing App',
        image: 'https://50projects50days.com/img/projects-img/22-drawing-app.png',
        link: 'DrawingApp',
    },
    {
        id: 23,
        title: 'Kinetic Loader',
        image: 'https://50projects50days.com/img/projects-img/23-kinetic-loader.png',
        link: 'KineticLoader',
    },
    {
        id: 24,
        title: 'Content Placeholder',
        image: 'https://50projects50days.com/img/projects-img/24-content-placeholder.png',
        link: 'ContentPlaceholder',
    },
    {
        id: 25,
        title: 'Sticky Navbar',
        image: 'https://50projects50days.com/img/projects-img/25-sticky-navbar.png',
        link: 'StickyNavbar',
    },
    {
        id: 26,
        title: 'Double Vertical Slider',
        image: 'https://50projects50days.com/img/projects-img/26-double-vertical-slider.png',
        link: 'DoubleVerticalSlider',
    },
    {
        id: 27,
        title: 'Toast Notification',
        image: 'https://50projects50days.com/img/projects-img/27-toast-notification.png',
        link: 'ToastNotification',
    },
    {
        id: 28,
        title: 'Github Profiles',
        image: 'https://50projects50days.com/img/projects-img/28-github-profiles.png',
        link: 'GithubProfiles',
    },
    {
        id: 29,
        title: 'Double Click Heart',
        image: 'https://50projects50days.com/img/projects-img/29-double-click-heart.png',
        link: 'DoubleClickHeart',
    },
    {
        id: 30,
        title: 'Auto Text Effect',
        image: 'https://50projects50days.com/img/projects-img/30-auto-text-effect.png',
        link: 'AutoTextEffect',
    },
    {
        id: 31,
        title: 'Password Generator',
        image: 'https://50projects50days.com/img/projects-img/31-password-generator.png',
        link: 'PasswordGenerator',
    },
    {
        id: 32,
        title: 'Good Cheap Fast',
        image: 'https://50projects50days.com/img/projects-img/32-good-cheap-fast.png',
        link: 'GoodCheapFast',
    },
    {
        id: 33,
        title: 'Notes App',
        image: 'https://50projects50days.com/img/projects-img/33-notes-app.png',
        link: 'NotesApp',
    },
    {
        id: 34,
        title: 'Animated Countdown',
        image: 'https://50projects50days.com/img/projects-img/34-animated-countdown.png',
        link: 'AnimatedCountdown',
    },
    {
        id: 35,
        title: 'Image Carousel',
        image: 'https://50projects50days.com/img/projects-img/35-image-carousel.png',
        link: 'ImageCarousel',
    },
    {
        id: 36,
        title: 'Hoverboard',
        image: 'https://50projects50days.com/img/projects-img/36-hoverboard.png',
        link: 'Hoverboard',
    },
    {
        id: 37,
        title: 'Pokedex',
        image: 'https://50projects50days.com/img/projects-img/37-pokedex.png',
        link: 'Pokedex',
    },
    {
        id: 38,
        title: 'MobileTabNavigation',
        image: 'https://50projects50days.com/img/projects-img/38-mobile-tab-navigation.png',
        link: 'MobileTabNavigation',
    },
    {
        id: 39,
        title: 'PasswordStrengthBackground',
        image: 'https://50projects50days.com/img/projects-img/39-password-strength-background.png',
        link: 'PasswordStrengthBackground',
    },
    {
        id: 40,
        title: '3dBackgroundBoxes',
        image: 'https://50projects50days.com/img/projects-img/40-3d-background-boxes.png',
        link: '3dBackgroundBoxes',
    },
    {
        id: 41,
        title: 'VerifyAccountUi',
        image: 'https://50projects50days.com/img/projects-img/41-verify-account-ui.png',
        link: 'VerifyAccountUi',
    },
    {
        id: 42,
        title: 'LiveUserFilter',
        image: 'https://50projects50days.com/img/projects-img/42-live-user-filter.png',
        link: 'LiveUserFilter',
    },
    {
        id: 43,
        title: 'FeedbackUiDesign',
        image: 'https://50projects50days.com/img/projects-img/43-feedback-ui-design.png',
        link: 'FeedbackUiDesign',
    },
    {
        id: 44,
        title: 'RangeSlider',
        image: 'https://50projects50days.com/img/projects-img/44-range-slider.png',
        link: 'RangeSlider',
    },
    {
        id: 45,
        title: 'NetflixMobileNavigation',
        image: 'https://50projects50days.com/img/projects-img/45-netflix-mobile-navigation.png',
        link: 'NetflixMobileNavigation',
    },
]
